### ISSUE TITLE
Error require of ES Module not supported

### ISSUE THREAD

**Issue by MickL** [sindresorhus/serialize-error#82]
Since 9.x (I also tried 10.x and 11.x) when importing serialize-error:

```
import { serializeError } from 'serialize-error';
```

I get the following error:

> Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/mick/git/myproject/node_modules/serialize-error/index.js from /Users/mick/myproject/src/myfile.ts not supported.
> Instead change the require of index.js in /Users/myproject/myfile.ts to a dynamic import() which is available in all CommonJS modules.

It works when building with `tsc` but not when starting with `ts-node`. Any idea what this could be? I dont find any `require()` somewhere...

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by MickL** [comment]
Hey @sindresorhus I dont know how this helps. I dont use any `require()` anywhere, I am on latest NodeJS.

**Comment by papb** [comment]
Did you read the [How can I make my TypeScript project output ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm) section?

**Comment by MickL** [comment]
Yes I did read it twice. It happens even in a blank new NestJS project as shown above.

**Comment by MickL** [comment]
It is "weird" that I have more than 200 packages installed but serialize-error is the only one producing this error

**Comment by papb** [comment]
After re-reading your post and seeing this...

> It works when building with tsc but not when starting with ts-node.

...and assuming [you've already read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-ts-node), I suggest you open an issue on ts-node or [comment on this one](https://github.com/TypeStrong/ts-node/issues/1007)

**Comment by papb** [comment]
Another idea: try to install and use another of Sindre's small ESM packages, such as [alpha-sort](https://github.com/sindresorhus/alpha-sort), and see if they work. Maybe Sindre made a mistake when moving to ESM in this specific package? Since both packages are small, perhaps you can spot the issue yourself and send a PR.

**Comment by U-4-E-A** [comment]
I am having the same issue. Did you find a way to solve this? Thanks.

**Comment by MickL** [comment]
Actually I stayed on 8.1.

We have 5+ Nest / TypeScript projects with hundreds of dependencies and this is the only one making problems and as I wrote above it is easy to reproduce.

**Comment by U-4-E-A** [comment]
> Actually I stayed on 8.1.
> 
> We have 5+ Nest / TypeScript projects with hundreds of dependencies and this is the only one making problems and as I wrote above it is easy to reproduce. If you find anything please post it here, thanks!

I've rolled back to 8.1 as well. I have also looked at the v11 repo and have started a process of converting it to my own module, possibly in Typescript. If I get any further along with that and have something functional, I will give you a shout. Given that the package is not updated very often, it might just be preferable to maintain my own repo as a copy of this one and check back here for updates from time to time.

**Comment by twosdai** [comment]
I have also rolled back to: `"serialize-error": "^8.1.0"` and this fixed the problem for me. 

FWIW running: 
`"@nestjs/core": "^9.2.1",`
`Node: v14.21.2`
`"ts-node": "^10.0.0"`

**Comment by MickL** [comment]
@sindresorhus could you please reopen as so many people are reporting the same issue?

**Comment by pauliesnug** [comment]
This is a bit silly imo, it really doesn't hurt anyone to just keep using CommonJS, especially for people who keep CommonJS in their own libraries for backwards compatibility etc. By switching to "pure ESM" suddenly, it just comes across as very annoying and unnecessary. Correct me if I'm wrong but if EJS and CommonJS can import CommonJS modules, but CommonJS can't import EJS modules, why not just keep using CommonJS modules and keep support for both?

**Comment by pauliesnug** [comment]
For reference, I encountered this problem when using `jest` and `ts-jest`, so, it seems like a pretty widespread problem considering those are very popular packages

**Comment by twosdai** [comment]
I fussed around with it more and the following statement works for me instead of the normal imports in 11.x for serialize-error

```js
            const { serializeError } = await (eval(`import('serialize-error')`) as Promise<
                typeof import('serialize-error')
            >);
```

The more I've dug into this the more I'm leaning toward this not being a library specific issue. Rather its an issue within the JS community about handling ESM modules appropriately. 

I got the idea for that bit of code from the following SO: https://stackoverflow.com/questions/70545129/compile-a-package-that-depends-on-esm-only-library-into-a-commonjs-package

While not elegant I have a feeling until TS-Node offers support for transpiling to ESM this won't be easily solved. Nor should we expect the library maintainer to fix it, since its not an issue with the library, rather the transpilation process from TS -> JS for ESM modules.

**Comment by papb** [comment]
@twosdai But if you're right, why would this be happening to `serialize-error` only?

Also, why use `eval` in your code? Why not simply `const { serializeError } = await import('serialize-error')`?

**Comment by twosdai** [comment]
The eval and string are necessary because TS will still transpile the code if: `const { serializeError } = await import('serialize-error')`  is present. Which leads to the same ESM importing issue.  In the SO comment I [linked](https://github.com/sindresorhus/serialize-error/issues/82#issuecomment-1461046915) the post goes into it a bit deeper. 

For as to why _this module_, in _this place_, in the _specific point in time_, localized in _this specific repo_. *shrug.  Its an ESM module import issue for transpiling, I'm not sure if any of the other repo's that I've installed are actually using ESM modules and this is just the first one in a long line of breaking dependencies, or if there is a specific bug present in ts-node for transpilation. 

As far as I can see between the [diff](https://github.com/sindresorhus/serialize-error/compare/v8.1.0...v11.0.0) of the `8.1.0` release to the current `11.0.0` release. There isn't anything obvious that is incorrect in the repo, and the only real change is exporting this as ESM. Which _should_ be transpiled correctly but isn't. Leading me to believe that its an issue in ts-node's transpilation system. Which anecdotally (I don't have the GH issues on hand) has varying levels of support and completeness.

**Comment by NtTestAlert** [comment]
Like almost every sindresorhus/* package lately, this one also does not work with jest... Probably same problem.
And while I understand why and that it is not a problem with the lib itself, the bottomline for me sadly is I won't use it.

**Comment by papb** [comment]
> since its not an issue with the library, rather the transpilation process from TS -> JS for ESM modules.

@twosdai Is there any issue open in TS for this?

**Comment by twosdai** [comment]
@papb https://github.com/TypeStrong/ts-node/issues/1007 
I believe this is the issue where they talk about the relative completeness of the feature, its still open and the discussion is still active which leads me to believe that its not fully complete.

**Comment by Torrichel** [comment]
Having the same problem.
Downgrading to 8.1.0 helped.

  "dependencies": {
  "serialize-error": "8.1.0",
    "@types/express": "^4.17.17",
    "@types/jest": "^29.5.2",
    "@types/node": "^20.1.0",
    "jest": "^29.5.0",
    "ts-jest": "^29.1.0",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.0.4"
  }

**Comment by twosdai** [comment]
@Torrichel  Did you try 
```
            const { serializeError } = await (eval(`import('serialize-error')`) as Promise<
                typeof import('serialize-error')
            >);
```
for importing instead? just in case you want to keep the new version.

**Comment by crizo23** [comment]
> @Torrichel Did you try
> 
> ```
>             const { serializeError } = await (eval(`import('serialize-error')`) as Promise<
>                 typeof import('serialize-error')
>             >);
> ```
> 
> for importing instead? just in case you want to keep the new version.

oooh typescript. I tried this solution, then of course I got 
`SyntaxError: await is only valid in async functions and the top level bodies of modules
`

wrapped it in an async IIFE and got 
```
Object.defineProperty(exports, "__esModule", { value: true });
                   
ReferenceError: exports is not defined in ES module scope
```
